"""VPS provisioning: cloud-init generation, Hetzner hcloud CLI wrapper, SSH deployment helpers

Docs: https://vedicreader.github.io/vpseasycore.html.md"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['mp', 'dock_cmd', 'Multipass', 'deploy_mp', 'keygen', 'gen_key', 'vps_init', 'multi_init', 'Hetzner', 'run_ssh',
           'sync', 'chk_docker', 'deploy', 'wait_ssh', 'chk_cloud_init', 'wait_ready', 'hetzner_deploy',
           'load_pub_keys', 'vols_to_binds', 'caddy_stack', 'mv_skill_md']

# %% ../nbs/00_core.ipynb #8795cffa
import getpass, json, os, shlex, subprocess, tempfile, time
from contextlib import contextmanager, suppress
from dockeasy import Cli, env_get, Compose, caddy_svc, cloudflared_svc, fasthtml_app
from fastcore.all import L, Path, run, listify, AttrDict, AttrDictDefault, delegates, modified_env
from fastcloudinit.core import cloud_init_base, cloud_init_config, user, runcmd, reboot
from hcloud import Client
from hcloud.images import Image
from hcloud.server_types import ServerType
from hcloud.locations import Location
from hcloud.ssh_keys import SSHKey

# %% ../nbs/00_core.ipynb #67f2b54ac2a375f9
class Multipass(Cli):
    'Wrap multipass CLI: manage local Ubuntu VMs for testing'
    def _run(self, cmd, *args): return run('multipass', cmd, *args)
    def launch(self,name,image='24.04',cpus=1,memory='1G',disk='10G',cloud_init:AttrDict=None, mounts=None) -> AttrDict:
        'Launch a VM. cloud_init: AttrDict(yaml, key) from multi_init() or vps_init(). Returns AttrDict(name, key).'
        args = ['multipass', 'launch', image, '-n', name, '-c', str(cpus), '-m', memory, '-d', disk]
        for hp, vp in (mounts or {}).items(): args += ['--mount', f'{hp}:{vp}']
        if cloud_init: args += ['--cloud-init', '-']
        subprocess.run(args, input=cloud_init.yaml if cloud_init else None, text=True, check=True)
        return AttrDict(name=name, key=cloud_init.key if cloud_init else None)

    def vms(self, running=False):
        'List VM names. running=True filters to Running state.'
        lst = L(json.loads(self('list', '--format', 'json')).get('list', []))
        if running: lst = lst.filter(lambda v: v.get('state') == 'Running')
        return list(lst.itemgot('name'))

    def ip(self, name) -> str:
        'Get IPv4 address of a VM.'
        return json.loads(self('info', name, '--format', 'json'))['info'][name]['ipv4'][0]

    def exec_(self, name, *cmd) -> str:
        'Run a command in a VM.'
        return self('exec', name, '--', *cmd)

    def rm(self, name, purge=True) -> None:
        'Delete a VM.'
        self('delete', '--purge' if purge else '', name)

mp = Multipass()

def deploy_mp(name, src, path='/srv/app', key=None, build=True, verbose=True) -> None:
    'Sync local directory into a Multipass VM and run docker compose up -d.'
    mp.exec_(name, 'sudo', 'install', '-d', '-o', 'deploy', '-g', 'deploy', path)
    deploy(mp.ip(name), src, path, key=key, name=name, build=build, verbose=verbose)

# %% ../nbs/00_core.ipynb #d9b26e5a
dock_cmd = ['curl -fsSL https://get.docker.com | sh', 'usermod -aG docker {username}','systemctl enable --now docker']
def keygen(path): return ['ssh-keygen', '-t', 'ed25519', '-f', str(path), '-N', '', '-q']
def _mk_kp(h,pub): return AttrDictDefault(pub_str=listify(pub)) if pub else gen_key(h)
def gen_key(slug, key_dir=None):
    'Generate ed25519 key pair at <key_dir>/<slug>. Overwrites existing. Returns AttrDict(key, pub, pub_str).'
    d = Path(key_dir or Path.home()/'.ssh')
    priv, pub = d/slug, d/f'{slug}.pub'
    subprocess.run(keygen(priv), input='y\n', text=True, capture_output=True, check=True)
    return AttrDict(key=priv, pub=pub, pub_str=[pub.read_text().strip()])

def vps_init(hostname, pub_keys=None, username='deploy', docker=True, pkgs=None, cmds=None, **kw):
    'Cloud-init for a fresh VPS. pub_keys=None → auto-generates ed25519 key pair. Returns AttrDict(yaml, key).'
    kp = _mk_kp(hostname, pub_keys)
    cmds = [c.format(username=username) for c in dock_cmd] if docker else [] + listify(cmds)
    pkgs = ['curl', 'fail2ban', 'unattended-upgrades'] + listify(pkgs)
    yaml = cloud_init_config(hostname=hostname,username=username,pub_keys=kp.pub_str,packages=pkgs,cmds=cmds,**kw)
    return AttrDict(yaml=yaml, key=kp.key)

# %% ../nbs/00_core.ipynb #bqtzq0gu82l
def multi_init(hostname, pub_keys=None, username='deploy', docker=True, pkgs=None, cmds=None):
    'Cloud-init for Multipass local VMs. pub_keys=None → auto-generates ed25519 key pair. Returns AttrDict(yaml, key).'
    kp = _mk_kp(hostname, pub_keys)
    cmds = [c.format(username=username) for c in dock_cmd] if docker else [] + listify(cmds)
    pkgs = ['curl'] + listify(pkgs)
    kw = {**runcmd(cmds), **reboot()} if cmds else {}
    yaml = cloud_init_base(hostname, packages=pkgs, users=[user(username, kp.pub_str)], **kw)
    return AttrDict(yaml=yaml, key=kp.key)

# %% ../nbs/00_core.ipynb #a2e72839
class Hetzner:
    'Hetzner Cloud VPS provider via hcloud Python SDK. Token read from HCLOUD_TOKEN by default.'
    def __init__(self, token=None):
        token = token or env_get('HCLOUD_TOKEN')
        if not token: raise ValueError('HCLOUD_TOKEN environment variable not set')
        self._c = Client(token=token)

    def servers(self) -> list:
        'List servers as [{name, ip, status}]'
        return L(self._c.servers.get_all()).map(lambda s: dict(name=s.name, ip=s.public_net.ipv4.ip, status=s.status))

    def server_ip(self, name) -> str:
        'Get public IPv4 of a server by name'
        s = self._c.servers.get_by_name(name)
        if not s: raise ValueError(f'Server {name!r} not found')
        return s.public_net.ipv4.ip

    def create(self, name, image='ubuntu-24.04', server_type='cx23', location=None, cloud_init=None, ssh_keys=None):
        '''Create a server. cloud_init: YAML string or AttrDict(yaml, key) from vps_init(). Returns AttrDict(ip, name, key, resp).
        NOTE: ssh_keys are Hetzner-registered keys injected into the root user only — they do NOT grant access to the
        deploy user created by cloud_init. Pass ssh_keys only when cloud_init is None (root-only access).'''
        if cloud_init is not None and ssh_keys:
            raise ValueError(
                'ssh_keys and cloud_init are conflicting strategies: ssh_keys grants root access only, '
                'while cloud_init creates a deploy user with its own key. '
                'Use cloud_init alone (key is in the returned AttrDict) or ssh_keys alone for root access.'
            )
        key = None
        if isinstance(cloud_init, AttrDict): key, cloud_init = cloud_init.key, cloud_init.yaml
        resp = self._c.servers.create(
            name=name,
            server_type=ServerType(name=server_type),
            image=Image(name=image),
            location=Location(name=location) if location else None,
            user_data=cloud_init,
            ssh_keys=[SSHKey(name=k) for k in (ssh_keys or [])],
        )
        return AttrDict(ip=resp.server.public_net.ipv4.ip, name=name, key=key, resp=resp)

    def delete(self, name) -> None:
        'Delete a server by name'
        s = self._c.servers.get_by_name(name)
        if s: s.delete()

    def keys(self) -> list:
        'List SSH keys as [{name, fingerprint}]'
        return L(self._c.ssh_keys.get_all()).map(lambda k: dict(name=k.name, fingerprint=k.fingerprint))

    def key_names(self) -> list:
        'Return SSH key name strings for use in create(ssh_keys=[...]) — root access only, not for deploy user'
        return [k['name'] for k in self.keys()]

# %% ../nbs/00_core.ipynb #0f2c0407
def _ssh(host, user, key, port):
    a = ['ssh', '-o', 'StrictHostKeyChecking=accept-new']
    if key: a += ['-i', str(key)]
    if port != 22: a += ['-p', str(port)]
    return a + [f'{user}@{host}']

def _res_key(key=None, name=None):
    'Resolve SSH key: explicit path > name slug (~/.ssh/<name>) > None. Raise if file with slug missing.'
    if key: return str(key)
    if not name: return None
    p = Path.home()/'.ssh'/name
    if not p.exists(): raise FileNotFoundError(f'No SSH key at {p} — run gen_key({name!r}) first')
    print('Resolved SSH key from name slug:', p)
    return str(p)

def _resolve_pass(v, prompt):
    "Return v, or prompt via getpass if v is True."
    return getpass.getpass(prompt) if v is True else v

@contextmanager
def _askpass_env(pw):
    "Sets SSH_ASKPASS env for key passphrase or server password auth. No-op if pw is None."
    if not pw: yield; return
    fd, path = tempfile.mkstemp(prefix='.vpseasy_askpass_', suffix='.sh')
    try:
        os.write(fd, f'#!/bin/sh\necho {shlex.quote(pw)}\n'.encode())
        os.close(fd)
        os.chmod(path, 0o700)
        with modified_env('DISPLAY', SSH_ASKPASS=path, SSH_ASKPASS_REQUIRE='force'): yield
    finally:
        with suppress(FileNotFoundError): os.unlink(path)

@delegates(run, keep=True)
def run_ssh(host, *cmds, user='deploy', key=None, name=None, port=22, key_pass=None, password=None, check=True, verbose=False, **kwargs):
    'Run commands on remote host via SSH. key_pass= for key passphrase, password= for server password auth. Pass True to either to prompt.'
    key_pass = _resolve_pass(key_pass, 'SSH key passphrase: ')
    password = _resolve_pass(password, 'SSH password: ')
    with _askpass_env(key_pass or password):
        r = run(_ssh(host, user, _res_key(key, name), port) + [' && '.join(cmds)], ignore_ex=not check, **kwargs)
    if verbose: print(f'Ran SSH command on {host}: {" && ".join(cmds)} → {r}')
    return r


def sync(host, src='.', path='/srv/app', user='deploy', key=None, name=None, include=None, exclude=None,
         extra=None, key_pass=None, password=None, verbose=False):
    'Rsync local src to remote host:path. include= whitelist patterns, exclude= blacklist patterns. extra= extra rsync flags e.g. "--checksum" or ["--ignore-times","--partial"].'
    key_pass = _resolve_pass(key_pass, 'SSH key passphrase: ')
    password = _resolve_pass(password, 'SSH password: ')
    a = f'[ -d {path} -a -w {path} ] || (sudo mkdir -p {path} && sudo chown {user}:{user} {path})'
    run_ssh(host, a, user=user, key=key, name=name, key_pass=key_pass, password=password)
    if verbose: print(f'Ensured remote path {path} exists and is writable by {user}')
    ssh_e = ' '.join(_ssh(host, user, _res_key(key, name), 22)[:-1])
    inc, exc = listify(include), listify(exclude)
    cmd = ['rsync', '-az' + ('m' if inc else ''), '--delete', '-e', ssh_e, *listify(extra)]
    for p in exc: cmd += ['--exclude', p]
    if inc:
        for p in inc: cmd+=(['--include',p] if not p.endswith('/') else ['--include',p.rstrip('/'),'--include',p+'**'])
        cmd += ['--include', '*/', '--exclude', '*']
    cmd += [str(src).rstrip('/') + '/', f'{user}@{host}:{path}/']
    if verbose: print('Running rsync:', ' '.join(cmd))
    with _askpass_env(key_pass or password):
        run(cmd)
    if verbose: print('Rsync completed successfully')

def chk_docker(host, u='deploy', k=None, name=None, key_pass=None, password=None, verbose=False) -> bool:
	'Verify docker daemon is running and user can run containers.'
	try:
		r = run_ssh(host, 'docker info', user=u, key=k, name=name, key_pass=key_pass, password=password)
		if verbose: print(f'Docker info: {r.strip()}')
		return True
	except Exception as e:
		if verbose: print(f'Docker check failed: {e}')
		return False

def _chk_compose(host, path, f='docker-compose.yml', u='deploy', k=None, name=None, key_pass=None, password=None, verbose=False) -> bool:
	'Check if Dockerfile exists in the remote path.'
	try:
		r = run_ssh(host, f'ls {path}/{f}', user=u, key=k, name=name, key_pass=key_pass, password=password)
		if verbose: print(f'docker-compose check output: {r.strip()}')
		return 'docker-compose' in r
	except Exception as e:
		if verbose: print(f'docker-compose check failed: {e}')
		return False

def deploy(host, src='.', path='/srv/app', user='deploy', build=True, key=None, name=None,
           include=None, exclude=None, extra=None, key_pass=None, password=None, verbose=False):
    'Sync src to host via rsync then docker compose up if docker is available. extra= extra rsync flags forwarded to sync().'
    key_pass = _resolve_pass(key_pass, 'SSH key passphrase: ')
    password = _resolve_pass(password, 'SSH password: ')
    sync(host, src, path, user, key=key, name=name, include=include, exclude=exclude, extra=extra, key_pass=key_pass, password=password, verbose=verbose)
    kw = dict(host=host, u=user, k=key, name=name, key_pass=key_pass, password=password, verbose=verbose)
    if not (chk_docker(**kw) and _chk_compose(path=path,**kw)): return
    a = f'cd {path} && docker compose up -d --remove-orphans' + (' --build' if build else '')
    r = run_ssh(host, a, user=user, key=key, name=name, key_pass=key_pass, password=password, verbose=verbose)
    if verbose: print('docker compose ran' + (' with build' if build else ''), '→', r.strip())


# %% ../nbs/00_core.ipynb #q4e3dvg4au
def wait_ssh(host, u='deploy', k=None, name=None, p=22, tout=300, interval=5, key_pass=None, password=None, verbose=True):
    'Poll SSH until connection succeeds or raises TimeoutError.'
    key_pass = _resolve_pass(key_pass, 'SSH key passphrase: ')
    password = _resolve_pass(password, 'SSH password: ')
    dl = time.time() + tout
    while time.time() < dl:
        try:
            run_ssh(host, 'true', user=u, key=k, name=name, port=p, key_pass=key_pass, password=password)
            if verbose: print(f'SSH to host {host} check succeeded')
            return True
        except Exception as e:
            if verbose: print(f'SSH to {host} not ready yet, retrying in {interval}s).Error:{e}')
            time.sleep(interval)
    raise TimeoutError(f'SSH to {host} not ready after {tout}s')

def chk_cloud_init(host, u='deploy', k=None, name=None, key_pass=None, password=None, verbose=True) -> str:
    'Return cloud-init status: done|running|error|unknown. check=False handles exit code 2 (done-with-warnings) on Ubuntu 24.04.'
    o = run_ssh(host, 'sudo cloud-init status', user=u, key=k, name=name,
        key_pass=key_pass, password=password, check=False, verbose=verbose)
    o = o[1].strip()
    return o.split(': ', 1)[-1].strip() if ': ' in o else (o or 'unknown')


# %% ../nbs/00_core.ipynb #0d506066
def wait_ready(host,
               u='deploy',
               k=None,
               name=None,
               tout=300,
               interval=5,
               retries=2,
               key_pass=None,
               password=None,
               verbose=False
):
    'Wait for SSH then poll cloud-init until done. Retries cloud-init polling up to `retries` times before raising TimeoutError.'
    key_pass = _resolve_pass(key_pass, 'SSH key passphrase: ')
    password = _resolve_pass(password, 'SSH password: ')
    wait_ssh(host, u=u, k=k, name=name, tout=tout, interval=interval, key_pass=key_pass,
             password=password, verbose=verbose)
    for a in range(retries + 1):
        dl = time.time() + tout
        while time.time() < dl:
            status = chk_cloud_init(host, u=u, k=k, name=name, key_pass=key_pass, password=password)
            if verbose: print(f'cloud-init status: {status}')
            if status == 'done': return True
            if status == 'error': raise RuntimeError(f'cloud-init failed on {host}')
            time.sleep(interval)
        if a < retries: print(f'cloud-init on {host} still running after {tout}s — retrying ({a+1}/{retries}) ...')
    raise TimeoutError(f'cloud-init on {host} not done after {tout * (retries + 1)}s ({retries + 1} attempts)')

# %% ../nbs/00_core.ipynb #2bf3f571
def hetzner_deploy(name, # server name (also used for SSH key slug if key not given)
                   src,  # local path to sync and deploy
                   hz=None, # optional Hetzner() instance — creates one if not given
                   image='ubuntu-24.04', # Hetzner image slug
                   server_type='cx23', # Hetzner server type slug
                   location=None, # Hetzner location slug e.g. 'hel1' (optional)
                   path='/srv/app', # remote path to sync to and deploy at
                   build=True, # whether to pass --build to docker compose up
                   include=None, # rsync include (whitelist) patterns
                   exclude=None, # rsync exclude (blacklist) patterns
                   extra=None, # extra rsync flags forwarded to sync() e.g. '--checksum' or ['--ignore-times','--partial']
                   key_pass=None, # passphrase for the SSH key, if it's encrypted
                   password=None, # server password for SSH auth (alternative to key-based auth)
                   tout=600, # seconds to wait for SSH and cloud-init each before retrying (default 10 minutes)
                   retries=2, # cloud-init retries before giving up and raising TimeoutError
                   verbose=True # whether to print verbose logs during wait and deploy steps
):
    'Full pipeline: provision Hetzner VPS (idempotent) → wait for cloud-init → deploy. Returns AttrDict(ip, name, key).'
    key_pass = _resolve_pass(key_pass, 'SSH key passphrase: ')
    password = _resolve_pass(password, 'SSH password: ')
    hz = hz or Hetzner()
    ex = hz._c.servers.get_by_name(name)
    if ex:
        ip, key = ex.public_net.ipv4.ip, _res_key(name=name)
        if verbose: print(f'Server {name} already exists at {ip}, checking cloud-init ...')
        wait_ready(ip, k=key, tout=tout, retries=retries, key_pass=key_pass, password=password, verbose=verbose)
    else:
        ci = vps_init(name)
        svr = hz.create(name, image=image, server_type=server_type, location=location, cloud_init=ci)
        ip, key = svr.ip, svr.key
        subprocess.run(['ssh-keygen', '-R', ip], capture_output=True)
        if verbose: print(f'Server {name} provisioning at {ip} ...')
        wait_ready(ip, k=key, tout=tout, retries=retries, key_pass=key_pass, password=password, verbose=verbose)
    deploy(ip, src, path=path, build=build, key=key, include=include, exclude=exclude,
           extra=extra, key_pass=key_pass, password=password, verbose=verbose)
    return AttrDict(ip=ip, name=name, key=key)

# %% ../nbs/00_core.ipynb #0929rkcanuri
def load_pub_keys(paths=None) -> list:
    'Load SSH public key strings. paths=None → auto-detect from ~/.ssh/id_*.pub'
    paths = paths or list(Path.home().glob('.ssh/id_*.pub'))
    return [Path(p).read_text().strip() for p in listify(paths) if Path(p).exists()]

# %% ../nbs/00_core.ipynb #c46800d1
def vols_to_binds(vols):
    'Convert ["/app/data"] → ["./data:/app/data"] for docker compose bind mounts'
    return [f'./{v.split("/")[-1]}:{v}' for v in listify(vols)]

def caddy_stack(domain, df, vols=None, env_file='.env', cloudflared=True, root=None, conf=None, **kw):
    '''Compose with app + caddy + optional cloudflared, web network, caddy volumes.
    df: Dockerfile instance. root: if given, saves Dockerfile + docker-compose.yml there. **kw passed to caddy_svc.'''
    root = Path(root if root else '.')
    df.save(Path(root)/'Dockerfile')
    v,env = vols_to_binds(vols) if vols else None, listify(env_file) if env_file else None
    c = (Compose()
         .svc('app', build=df, volumes=v, env_file=env, restart='unless-stopped', networks=['web'])
         .svc('caddy', **caddy_svc(domain, cloudflared=cloudflared, conf=conf or root/'Caddyfile', **kw)))
    if cloudflared: c = c.svc('cloudflared', **cloudflared_svc(url='http://caddy'))
    c = c.network('web').volume('caddy_data').volume('caddy_config')
    if root: c.save(root/'docker-compose.yml')
    return c

# %% ../nbs/00_core.ipynb #37f0a632
def mv_skill_md(dry_run=True, dir=None) -> None:
    'Copy bundled SKILL.md to .agents/skills/vpseasy/ and ~/.claude/skills/vpseasy/'
    base = Path(__file__).parent if '__file__' in globals() else Path.cwd()
    src = base/'SKILL.md'
    if not src.exists(): return
    root = Path(dir or '.')
    ts = [root/'.agents/skills/vpseasy/SKILL.md',
          Path.home()/'.claude/skills/vpseasy/SKILL.md']
    if dry_run: print(f'Would copy to: {[str(p) for p in ts]}')
    else: [p.mk_write(src.read_text(encoding='utf-8')) for p in ts]
    if not dry_run: print(f'Installed → {[str(p) for p in ts]}')
