"""VPS provisioning: cloud-init generation, Hetzner hcloud CLI wrapper, SSH deployment helpers"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_core.ipynb.

# %% auto #0
__all__ = ['mp', 'dock_cmd', 'Multipass', 'deploy_mp', 'gen_key', 'vps_init', 'multi_init', 'Hetzner', 'run_ssh', 'sync',
           'deploy', 'wait_ssh', 'chk_cloud_init', 'chk_docker', 'load_pub_keys', 'mv_skill_md']

# %% ../nbs/00_core.ipynb #8795cffa
import os, json, subprocess, time
from dockeasy import Cli
from fastcore.all import L, Path, run, listify, atomic_save, AttrDict
from fastcloudinit.core import cloud_init_base, cloud_init_config, user, runcmd, reboot
from hcloud import Client
from hcloud.images import Image
from hcloud.server_types import ServerType
from hcloud.locations import Location
from hcloud.ssh_keys import SSHKey

# %% ../nbs/00_core.ipynb #67f2b54ac2a375f9
class Multipass(Cli):
    'Wrap multipass CLI: manage local Ubuntu VMs for testing'
    def _run(self, cmd, *args): return run('multipass', cmd, *args)
    def launch(self,name,image='24.04',cpus=1,memory='1G',disk='10G',cloud_init:AttrDict=None, mounts=None) -> AttrDict:
        'Launch a VM. cloud_init: AttrDict(yaml, key) from multi_init() or vps_init(). Returns AttrDict(name, key).'
        args = ['multipass', 'launch', image, '-n', name, '-c', str(cpus), '-m', memory, '-d', disk]
        for hp, vp in (mounts or {}).items(): args += ['--mount', f'{hp}:{vp}']
        if cloud_init: args += ['--cloud-init', '-']
        subprocess.run(args, input=cloud_init.yaml if cloud_init else None, text=True, check=True)
        return AttrDict(name=name, key=cloud_init.key if cloud_init else None)

    def vms(self, running=False):
        'List VM names. running=True filters to Running state.'
        lst = L(json.loads(self('list', '--format', 'json')).get('list', []))
        if running: lst = lst.filter(lambda v: v.get('state') == 'Running')
        return list(lst.itemgot('name'))

    def ip(self, name) -> str:
        'Get IPv4 address of a VM.'
        return json.loads(self('info', name, '--format', 'json'))['info'][name]['ipv4'][0]

    def exec_(self, name, *cmd) -> str:
        'Run a command in a VM.'
        return self('exec', name, '--', *cmd)

    def rm(self, name, purge=True) -> None:
        'Delete a VM.'
        self('delete', '--purge' if purge else '', name)

    def transfer(self, src, dst) -> None:
        'Transfer files to/from a VM. Use "vmname:/path" for VM paths.'
        self('transfer', src, dst)

mp = Multipass()

def deploy_mp(name, src, path='/srv/app', build=True) -> str:
    'Sync local directory into a Multipass VM and run docker compose up -d.'
    mp.exec_(name, 'mkdir', '-p', path)
    mp.transfer(str(src).rstrip('/') + '/', f'{name}:{path}')
    cmd = ['docker', 'compose', '-f', f'{path}/docker-compose.yml', 'up', '-d', '--remove-orphans']
    if build: cmd.append('--build')
    return mp.exec_(name, *cmd)

# %% ../nbs/00_core.ipynb #d9b26e5a
dock_cmd = [
    'curl -fsSL https://get.docker.com | sh',
    'usermod -aG docker {username}',
    'systemctl enable --now docker',
]

def gen_key(slug, key_dir=None):
    'Generate ed25519 key pair at <key_dir>/<slug>. Overwrites existing. Returns AttrDict(key, pub, pub_str).'
    d = Path(key_dir or Path.home()/'.ssh')
    priv, pub = d/slug, d/f'{slug}.pub'
    priv.unlink(missing_ok=True); pub.unlink(missing_ok=True)
    subprocess.run(['ssh-keygen', '-t', 'ed25519', '-f', str(priv), '-N', ''], check=True, capture_output=True)
    return AttrDict(key=priv, pub=pub, pub_str=pub.read_text().strip())

def vps_init(hostname, pub_keys=None, username='deploy', docker=True, pkgs=None, cmds=None, **kw):
    'Cloud-init for a fresh VPS. pub_keys=None → auto-generates ed25519 key pair. Returns AttrDict(yaml, key).'
    kp = gen_key(hostname) if pub_keys is None else None
    pks = [kp.pub_str] if kp else listify(pub_keys)
    rcmds = list(cmds or [])
    if docker: rcmds = [c.format(username=username) for c in dock_cmd] + rcmds
    yaml = cloud_init_config(hostname=hostname, username=username, pub_keys=pks,
        packages=['curl', 'fail2ban', 'unattended-upgrades'] + list(pkgs or []), cmds=rcmds, **kw)
    return AttrDict(yaml=yaml, key=kp.key if kp else None)

# %% ../nbs/00_core.ipynb #bqtzq0gu82l
def multi_init(hostname, pub_keys=None, username='deploy', docker=True, pkgs=None, cmds=None):
    'Cloud-init for Multipass local VMs. pub_keys=None → auto-generates ed25519 key pair. Returns AttrDict(yaml, key).'
    kp = gen_key(hostname) if pub_keys is None else None
    pks = [kp.pub_str] if kp else listify(pub_keys)
    rcmds = list(cmds or [])
    if docker: rcmds = [c.format(username=username) for c in dock_cmd] + rcmds
    kw = {**runcmd(rcmds), **reboot()} if rcmds else {}
    yaml = cloud_init_base(hostname, packages=['curl'] + list(pkgs or []), users=[user(username, pks)], **kw)
    return AttrDict(yaml=yaml, key=kp.key if kp else None)

# %% ../nbs/00_core.ipynb #a2e72839
class Hetzner:
    'Hetzner Cloud VPS provider via hcloud Python SDK. Token read from HCLOUD_TOKEN by default.'
    def __init__(self, token=None):
        token = token or os.environ.get('HCLOUD_TOKEN')
        if not token: raise ValueError('HCLOUD_TOKEN environment variable not set')
        self._c = Client(token=token)

    def servers(self) -> list:
        'List servers as [{name, ip, status}]'
        return L(self._c.servers.get_all()).map(lambda s: dict(name=s.name, ip=s.public_net.ipv4.ip, status=s.status))

    def server_ip(self, name) -> str:
        'Get public IPv4 of a server by name'
        s = self._c.servers.get_by_name(name)
        if not s: raise ValueError(f'Server {name!r} not found')
        return s.public_net.ipv4.ip

    def create(self, name, image='ubuntu-24.04', server_type='cx23', location=None, cloud_init=None, ssh_keys=None):
        'Create a server. cloud_init: YAML string or AttrDict(yaml, key) from vps_init(). Returns AttrDict(ip, name, key, resp).'
        key = None
        if isinstance(cloud_init, AttrDict): key, cloud_init = cloud_init.key, cloud_init.yaml
        resp = self._c.servers.create(
            name=name,
            server_type=ServerType(name=server_type),
            image=Image(name=image),
            location=Location(name=location) if location else None,
            user_data=cloud_init,
            ssh_keys=[SSHKey(name=k) for k in (ssh_keys or [])],
        )
        return AttrDict(ip=resp.server.public_net.ipv4.ip, name=name, key=key, resp=resp)

    def delete(self, name) -> None:
        'Delete a server by name'
        s = self._c.servers.get_by_name(name)
        if s: s.delete()

    def keys(self) -> list:
        'List SSH keys as [{name, fingerprint}]'
        return L(self._c.ssh_keys.get_all()).map(lambda k: dict(name=k.name, fingerprint=k.fingerprint))

    def key_names(self) -> list:
        'Return SSH key name strings for use in create(ssh_keys=[...])'
        return [k['name'] for k in self.keys()]

# %% ../nbs/00_core.ipynb #0f2c0407
def _ssh_base(host, user, key, port):
    a = ['ssh', '-o', 'StrictHostKeyChecking=accept-new']
    if key: a += ['-i', str(key)]
    if port != 22: a += ['-p', str(port)]
    return a + [f'{user}@{host}']

def _resolve_key(key=None, name=None):
    'Resolve SSH key: explicit path > name slug (~/.ssh/<name>) > SSH_KEY_PATH env > SSH_PRIVATE_KEY env.'
    if key: return str(key)
    if name:
        p = Path.home()/'.ssh'/name
        if not p.exists(): raise FileNotFoundError(f'No SSH key at {p} — run gen_key({name!r}) first')
        return str(p)
    if p := os.environ.get('SSH_KEY_PATH'): return p
    pk = os.environ.get('SSH_PRIVATE_KEY')
    if not pk: return None
    if not (p := Path(f'/tmp/.vpseasy_{os.getuid()}.pem')).exists():
        with atomic_save(p, mode='w') as f: f.write(pk.strip() + '\n')
        os.chmod(p, 0o400)
    return str(p)

def run_ssh(host, *cmds, user='deploy', key=None, name=None, port=22, capture=False, check=True):
    'Run commands on remote host via SSH. capture=True returns stdout string.'
    r = subprocess.run(_ssh_base(host, user, _resolve_key(key, name), port) + [' && '.join(cmds)],
                       capture_output=capture, text=capture, check=check)
    return r.stdout if capture else r

def sync(host, src='.', path='/srv/app', user='deploy', key=None, name=None, include=None, exclude=None):
    'Rsync local src to remote host:path. include= whitelist patterns, exclude= blacklist patterns.'
    run_ssh(host, f'mkdir -p {path}', user=user, key=key, name=name)
    ssh_e = ' '.join(_ssh_base(host, user, _resolve_key(key, name), 22)[:-1])
    inc, exc = listify(include), listify(exclude)
    cmd = ['rsync', '-az' + ('m' if inc else ''), '--delete', '-e', ssh_e]
    for p in exc: cmd += ['--exclude', p]
    if inc:
        for p in inc: cmd += (['--include', p] if not p.endswith('/') else
                               ['--include', p.rstrip('/'), '--include', p + '**'])
        cmd += ['--include', '*/', '--exclude', '*']
    cmd += [str(src).rstrip('/') + '/', f'{user}@{host}:{path}/']
    subprocess.run(cmd, check=True)

def deploy(host, src='.', path='/srv/app', user='deploy', build=True, key=None, name=None,
           include=None, exclude=None):
    'Sync src to host via rsync then docker compose up.'
    sync(host, src, path, user, key=key, name=name, include=include, exclude=exclude)
    run_ssh(host, f'cd {path} && docker compose up -d --remove-orphans' + (' --build' if build else ''),
            user=user, key=key, name=name)

# %% ../nbs/00_core.ipynb #q4e3dvg4au
def wait_ssh(host, u='deploy', k=None, p=22, tout=120, interval=5):
    'Poll SSH until connection succeeds or raises TimeoutError.'
    dl = time.time() + tout
    while time.time() < dl:
        try: run_ssh(host, 'true', user=u, key=k, port=p); return True
        except: time.sleep(interval)
    raise TimeoutError(f'SSH to {host} not ready after {tout}s')

def chk_cloud_init(host, u='deploy', k=None) -> str:
    'Return cloud-init status: done|running|error|unknown'
    try:
        o = run_ssh(host, 'sudo cloud-init status', user=u, key=k, capture=True)
        return o.split(': ', 1)[-1].strip() if ': ' in o else o.strip()
    except Exception: return 'unknown'

def chk_docker(host, u='deploy', k=None) -> bool:
    'Verify docker daemon is running and user can run containers.'
    try: run_ssh(host, 'docker info', user=u, key=k); return True
    except Exception: return False

# %% ../nbs/00_core.ipynb #0929rkcanuri
def load_pub_keys(paths=None) -> list:
    'Load SSH public key strings. paths=None → auto-detect from ~/.ssh/id_*.pub'
    paths = paths or list(Path.home().glob('.ssh/id_*.pub'))
    return [Path(p).read_text().strip() for p in listify(paths) if Path(p).exists()]

# %% ../nbs/00_core.ipynb #37f0a632
def mv_skill_md(dry_run=True, dir=None) -> None:
    'Copy bundled SKILL.md to .agents/skills/vpseasy/ and ~/.claude/skills/vpseasy/'
    base = Path(__file__).parent if '__file__' in globals() else Path.cwd()
    src = base/'SKILL.md'
    if not src.exists(): return
    root = Path(dir or '.')
    ts = [root/'.agents/skills/vpseasy/SKILL.md',
          Path.home()/'.claude/skills/vpseasy/SKILL.md']
    if dry_run: print(f'Would copy to: {[str(p) for p in ts]}')
    else: [p.mk_write(src.read_text(encoding='utf-8')) for p in ts]
    if not dry_run: print(f'Installed → {[str(p) for p in ts]}')
